### PR TITLE
Fix empty file size issue + add test

### LINKED ISSUE #670: Empty file transfer freezes data channel
Repro steps:
1. Navigate to https://webrtc.github.io/samples/src/content/datachannel/filetransfer/
2. Click on 'Choose file'  and upload an empty file (file with no contents). Please see the attached empty file.txt
3. Observe that 'Send progress' and 'Receive progress' are not shown and no data transfer happens
   https://screenshot.googleplex.com/1psw89qWuRk.png
4. Console(Javascript) logs shows that data channels are open

Expected result: 
File transfer should happen even when file does not have any contents and data channel should be closed after the transfer

Actual result:
File is not transferred when there are no contents and data channel is kept open indefinitely. 
'Choose file' button is frozen making users unable to upload another file.
https://screenshot.googleplex.com/1psw89qWuRk.png

Chrome version: 
46.0.2490.71 (Official Build) (64-bit)

OS:
Linux Desktop

Logs:
This appears to be Chrome
common.js:8 7.170: Created local peer connection object localConnection
common.js:8 7.171: Created send data channel
common.js:8 7.172: Created remote peer connection object remoteConnection
common.js:8 7.175: Offer from localConnection 
v=0
o=- 3047940909882059690 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:OqwkB8YTXHr/Ao2+
a=ice-pwd:5aitgQaLhWTdFoRVXcENVQ8Y
a=fingerprint:sha-256 DC:19:3B:3C:50:FB:6A:A9:E1:9B:FE:E0:D5:8B:B7:BD:5F:A6:19:EE:BE:95:B2:2A:F5:DC:FB:9B:51:E2:9D:E5
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 7.176: Answer from remoteConnection 
v=0
o=- 8820750149763377843 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=ice-ufrag:iy70e0O7g0+lCTGo
a=ice-pwd:3mgODL11WI94Qys9wWhUMuVQ
a=fingerprint:sha-256 DC:19:3B:3C:50:FB:6A:A9:E1:9B:FE:E0:D5:8B:B7:BD:5F:A6:19:EE:BE:95:B2:2A:F5:DC:FB:9B:51:E2:9D:E5
a=setup:active
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 7.176: local ice callback
common.js:8 7.176: Local ICE candidate: 
candidate:2498979306 1 udp 2122262783 2620:0:1000:1502:788c:378:5d92:d93f 52232 typ host generation 0
common.js:8 7.176: local ice callback
common.js:8 7.177: Local ICE candidate: 
candidate:2614814290 1 udp 2122194687 172.22.104.141 44320 typ host generation 0
common.js:8 7.177: AddIceCandidate success.
common.js:8 7.178: AddIceCandidate success.
common.js:8 7.178: remote ice callback
common.js:8 7.178: Remote ICE candidate: 
 candidate:2498979306 1 udp 2122262783 2620:0:1000:1502:788c:378:5d92:d93f 58448 typ host generation 0
common.js:8 7.179: remote ice callback
common.js:8 7.179: Remote ICE candidate: 
 candidate:2614814290 1 udp 2122194687 172.22.104.141 34539 typ host generation 0
2common.js:8 7.180: AddIceCandidate success.
common.js:8 7.224: local ice callback
common.js:8 7.224: remote ice callback
common.js:8 7.227: Send channel state is: open
common.js:8 7.228: file is -emptyfile.txt 0 text/plain Thu Oct 22 2015 15:35:25 GMT-0700 (PDT)
common.js:8 7.228: Receive Channel Callback
common.js:8 7.229: Receive channel state is: open

### PR DESCRIPTION
**Pull request by KaptenJansson**
fixes #670

### CODE REVIEW

File: src/content/datachannel/filetransfer/js/main.js [hunk 1]
```diff
@@ -77,7 +85,7 @@ function sendData() {
   var chunkSize = 16384;
   var sliceFile = function(offset) {
     var reader = new window.FileReader();
-    reader.onload = (function() {
+    reader.onloadend = (function() {
```
Comment (fippo) [inline src/content/datachannel/filetransfer/js/main.js]: I think this still needs to be onload (which is called whenever a block is read)

**Comment by KaptenJansson** [comment]
@samdutton PTAL when you have a chance.

File: src/content/datachannel/datatransfer/js/main.js [hunk 2]
```diff
@@ -24,6 +24,13 @@ var bytesToSend = 0;
 
 sendButton.onclick = createConnection;
 
+// Prevent data sent to be set to 0.
+megsToSend.addEventListener('change', function(e) {
+  if (this.value === 0) {
+    megsToSend.value = 1;
```
Comment (samdutton) [inline src/content/datachannel/datatransfer/js/main.js]: This works, though it's not explicit (if someone tries out zero to see what happens). I think it would be better to disallow values of zero or less and display a status message that says that only positive values are allowed.

Also noticed that send channel state is never closed if zero is input, or a negative value.

(Frustrating that it's only possible to set the min spinner value or validate the input value, and not  possible to disallow values less than or equal to zero without extra code.)

**Comment by samdutton** [comment]
Works for me, but added question about how we handle disallowed values.

File: src/content/datachannel/filetransfer/js/main.js [hunk 3]
```diff
@@ -67,9 +68,20 @@ function onCreateSessionDescriptionError(error) {
 
 function sendData() {
   var file = fileInput.files[0];
+  console.log('Before File size is 0');
   trace('file is ' + [file.name, file.size, file.type,
```
Comment (samdutton) [inline src/content/datachannel/filetransfer/js/main.js:71]: Should `console.log('Before File size is 0');` be here? Slightly confusing.

Comment (KaptenJansson) [inline src/content/datachannel/filetransfer/js/main.js:71]: No ;) Left over from debugging.

File: src/content/datachannel/datatransfer/js/main.js (hunk 2 above)
Comment (KaptenJansson) [inline src/content/datachannel/datatransfer/js/main.js]: Valid point, I've changed it to be clearer and also it disables/enables the button, WDYT?

**Comment by samdutton** [comment]
LGTM apart from nitpick.
