### PR TITLE
Get audio context on user interaction. Right now it is created suspen…

### LINKED ISSUE #1317: "https://webrtc.github.io/samples/src/content/getusermedia/volume" page is not working as intended
## Browser affected
Google Chrome | 85.0.4170.0 (Official Build) (64-bit)
-- | --
Revision | c4613390bc059d8aab9d57828847f77fd0c0ef47-refs/branch-heads/4170@{#1}
OS | macOS Version 10.15.4 (Build 19E287)

## Description
https://webrtc.github.io/samples/src/content/getusermedia/volume Page is not working as intended.

## Steps to reproduce
1. Launch https://webrtc.github.io/samples/src/content/getusermedia/volume on Chrome Browser.
2. Warning message observed in the console  "main.js:23 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu"

## Expected results
When user speaks, the volume of the local media streams should fluctuate.

## Actual results
When user speaks, the volume of the local media streams do not fluctuate

### PR DESCRIPTION
**Pull request by jackzelenkin**
**Description**
On page load audio context is created suspended (https://goo.gl/7K7WLu) and audio meter shows nothing. Controls are need to create it on user interaction.

**Purpose**
Add buttons to let user `start`(create audio context)/`stop`(stop it) the audio meter. This is aimed to fix #1317

+ @alvestrand for review

### CODE REVIEW

**Comment by jackzelenkin** [comment]
This pull request is aimed to fix #1317

File: src/content/getusermedia/volume/js/main.js [hunk 1]
```diff
@@ -18,19 +23,14 @@ const instantValueDisplay = document.querySelector('#instant .value');
...
-  alert('Web Audio API not supported.');
-}
-
 // Put variables in global scope to make them available to the browser console.
 const constraints = window.constraints = {
   audio: true,
   video: false
 };
 
+var meterRefreshFn = null;
```
Comment (KaptenJansson) [inline src/content/getusermedia/volume/js/main.js]: What's the Fn part of the name? Function? Does not seem necessary but its just a nit.

**Review by KaptenJansson — APPROVED** [review]
I think you could also kept the old logic but done resume on a user action but this works too.

File: src/content/getusermedia/volume/js/main.js (hunk 1 above)
Comment (jackzelenkin) [reply src/content/getusermedia/volume/js/main.js]: Fixed the name.

**Review by KaptenJansson — APPROVED** [review]

**Review by KaptenJansson — APPROVED** [review]
LGTM

**Review by KaptenJansson — APPROVED** [review]

**Comment by KaptenJansson** [comment]
Seems to bugged out. I've approved.
